### ISSUE TITLE
Pedal Board Rev 2

### ISSUE THREAD

**Issue by jkominek** [jkominek/piano-conversion#40]
- [x] The TRS tips, which goes to the ADC inputs, have a series resistors on them, but we should add some caps to those signals, near the connector. This will help clean up the signal, and add ESD protection. 10 ohm series + 1uF should be a ~15kHz cutoff frequency, which is still higher frequency than necessary, but should help reduce aliasing, and keeps the cap size reasonable.
- [x] Convert to use of an STM32G0
- [x] We can add support for IRQ lines, now that there will be a tiny uC to detect changes. Add the header, and insert the transistor necessary to perform the pull downs.
- [x] Connect every single TRS signal (3 pins, 4 connectors) to a different ADC input on the STM32. By converting some of the pins on every connector to outputs and applying 0s and 1s appropriately, we can supply the power for the potentiometer in the pedal to work. Then the ADC can read the remaining pin per connector, and use that result.
  * more of a firmware issue, but start thinking now, what's the algorithm to automatically determine the pedal's configuration?
- [x] Bring out at least four of the ADC lines on header pins, along with VCC and GND, to facilitate connections to a broader range of sensors. Possibly all of the ADC lines.

**Comment by davidedelvento** [comment]
Perhaps add space for other kind of connectors as inputs, in addition to the TRS for external pedals. Some people might want to use a "regular" sensorboard to measure movements of something attached to salvaged acoustic pedals. The range of interesting movement for una corda, sostenuto and dampers is not very different from the hammers, so I'd expect three 1x boards working well for this use case, if this board is able to support them. No need for the more fancy stuff that you do for the hammers, IMHO.

**Comment by jkominek** [comment]
Hmm, I'd imagined attaching mechanical pots to such things... somehow, and then cables with TRS plugs. The other thought I'd had was encoders, either mechanical or magnetic, which wouldn't work with this design.

But somebody using optical reflectance is also reasonable. https://www.sparkfun.com/products/15334 would cover the simple case, with appropriate firmware support on the main board. There wouldn't the same smarts that this version has.

I'll think about making an alternative "simple sensor board", which would have space for the same STM32G0, appropriate I2C ports, the IRQ line, and then headers to get at all the other pins, along with some optional analog tidbits one could use, or not. Like a quad op amp, and some good-but-not-great LED drivers.

**Comment by davidedelvento** [comment]
> Hmm, I'd imagined attaching mechanical pots to such things... somehow, and then cables with TRS plugs. 

I see. I don't like mechanics, since all the leverage acting the pots need to be within well specifics ranges to operate correctly, but perhaps for just 2 or 3 as in this case it won't be so bad.

In my (*) view of what you are doing, I thought: an ADC measuring a potentiometer isn't that different from an ADC measuring the output of this thing https://www.sparkfun.com/products/11769 (which I am testing as a key sensor). Hence with limited work on your side, this very same board can support either the optical sensors, or the mechanically attached pots, or the commercial pedals based on pots.

(*): probably excessively simplified, as you have certainly noticed by my other comment about the op amp placement

**Comment by jkominek** [comment]
> an ADC measuring a potentiometer isn't that different from an ADC measuring the output of this thing

Yeah, that's true. There's no reason I can't stick some headers on this exposing the ADC lines, and bring out the +3V3 rail a couple of times of convenience. I will do exactly that.

> I don't like mechanics, since all the leverage acting the pots need to be within well specifics ranges to operate correctly

That's a good point. Pedals would be moving pots at low RPM, so they'd probably hold up, but there'd need to be some consideration for alignment just to get it working in the first place.

**Comment by jkominek** [comment]
Ok, added headers bringing out the ADC lines and some power, in 91a407f.

**Comment by jkominek** [comment]
dc4713c marked as rev 2 and ordered
