### ISSUE TITLE
Sensorboards hole spacing

### ISSUE THREAD

**Issue by davidedelvento** [jkominek/piano-conversion#50]
All the centered sensorboards have the holes at a distance of `20.2mm` from each other, rather than exactly `20.0mm` as I was expecting for the extrusions you and I are utilizing.

This might be intentional or my own measurement error, and in any case not a big deal since smaller than mechanical tolerances, but since I saw it, I am reporting it anyway.

**Comment by jkominek** [comment]
Thanks, probably bumped things around at some point when laying them out. I've added this onto the checklist for #44
